upstream mahdara {
  server 127.0.0.1:3062 fail_timeout=0;
}

server {
  listen 80;
  server_name mahdara.next-version.com;

  root /var/www/mahdara/client/dist;

  # Serve frontend SPA
  location / {
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  # Proxy API requests to Rails
  location /api/ {
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_redirect off;
    proxy_set_header Connection '';
    proxy_pass http://mahdara;
  }

  location ~ ^/(assets|packs)/|favicon.ico|robots.txt {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
  }

  # Compression
  gzip on;

  location ~* \.(?:css|js) {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
  }

  location ~* \.(?:jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|otf|eot)$ {
    access_log off;
    expires max;
    add_header Cache-Control public;
  }

  error_page 500 502 503 504 /500.html;
  client_max_body_size 50M;
  keepalive_timeout 10;

  access_log /var/log/nginx/mahdara.access.log;
  error_log /var/log/nginx/mahdara.error.log;
}
