export const PERMISSIONS = {
  EMPLOYEES_READ:           'employees:read',
  EMPLOYEES_CREATE:         'employees:create',
  EMPLOYEES_UPDATE:         'employees:update',
  EMPLOYEES_DELETE:         'employees:delete',
  EMPLOYEES_EXPORT:         'employees:export',
  CONTRACTS_CREATE:         'contracts:create',
  CONTRACTS_UPDATE:         'contracts:update',
  CONTRACTS_DELETE:         'contracts:delete',
  MAHDARAS_CREATE:          'mahdaras:create',
  MAHDARAS_UPDATE:          'mahdaras:update',
  MAHDARAS_DOWNLOAD:        'mahdaras:download',
  PAYMENT_BATCHES_READ:     'payment_batches:read',
  PAYMENT_BATCHES_CREATE:   'payment_batches:create',
  PAYMENT_BATCHES_CONFIRM:  'payment_batches:confirm',
  PAYMENT_BATCHES_DELETE:   'payment_batches:delete',
  PAYMENT_BATCHES_EXPORT:   'payment_batches:export',
  EMPLOYEE_TYPES_READ:      'employee_types:read',
  EMPLOYEE_TYPES_CREATE:    'employee_types:create',
  EMPLOYEE_TYPES_UPDATE:    'employee_types:update',
  EMPLOYEE_TYPES_DELETE:    'employee_types:delete',
  WILAYAS_READ:             'wilayas:read',
  WILAYAS_CREATE:           'wilayas:create',
  WILAYAS_UPDATE:           'wilayas:update',
  WILAYAS_DELETE:           'wilayas:delete',
  WILAYAS_IMPORT:           'wilayas:import',
  MOUGHATAA_READ:           'moughataa:read',
  MOUGHATAA_CREATE:         'moughataa:create',
  MOUGHATAA_UPDATE:         'moughataa:update',
  MOUGHATAA_DELETE:         'moughataa:delete',
  MOUGHATAA_IMPORT:         'moughataa:import',
  COMMUNES_READ:            'communes:read',
  COMMUNES_CREATE:          'communes:create',
  COMMUNES_UPDATE:          'communes:update',
  COMMUNES_DELETE:          'communes:delete',
  COMMUNES_IMPORT:          'communes:import',
  VILLAGES_READ:            'villages:read',
  VILLAGES_CREATE:          'villages:create',
  VILLAGES_UPDATE:          'villages:update',
  VILLAGES_DELETE:          'villages:delete',
  VILLAGES_IMPORT:          'villages:import',
  BANKS_READ:               'banks:read',
  BANKS_CREATE:             'banks:create',
  BANKS_UPDATE:             'banks:update',
  BANKS_DELETE:             'banks:delete',
  SALARY_AMOUNTS_READ:      'salary_amounts:read',
  SALARY_AMOUNTS_CREATE:    'salary_amounts:create',
  SALARY_AMOUNTS_DELETE:    'salary_amounts:delete',
  USERS_READ:               'users:read',
  USERS_CREATE:             'users:create',
  USERS_UPDATE:             'users:update',
  USERS_DELETE:             'users:delete',
  ROLES_READ:               'roles:read',
  ROLES_CREATE:             'roles:create',
  ROLES_UPDATE:             'roles:update',
  ROLES_DELETE:             'roles:delete',
};

export const PERMISSION_LABELS = {
  'employees:read':           'عرض الموظفين',
  'employees:create':         'إضافة موظف',
  'employees:update':         'تعديل موظف',
  'employees:delete':         'حذف موظف',
  'employees:export':         'تصدير الموظفين',
  'contracts:create':         'إضافة عقد',
  'contracts:update':         'تعديل عقد',
  'contracts:delete':         'حذف عقد',
  'mahdaras:create':          'إضافة محظرة',
  'mahdaras:update':          'تعديل محظرة',
  'mahdaras:download':        'تحميل وثيقة المحظرة',
  'payment_batches:read':     'عرض دفعات الدفع',
  'payment_batches:create':   'إنشاء دفعة دفع',
  'payment_batches:confirm':  'تأكيد دفعة الدفع',
  'payment_batches:delete':   'حذف دفعة الدفع',
  'payment_batches:export':   'تصدير دفعة الدفع',
  'employee_types:read':      'عرض أنواع الموظفين',
  'employee_types:create':    'إضافة نوع موظف',
  'employee_types:update':    'تعديل نوع موظف',
  'employee_types:delete':    'حذف نوع موظف',
  'wilayas:read':             'عرض الولايات',
  'wilayas:create':           'إضافة ولاية',
  'wilayas:update':           'تعديل ولاية',
  'wilayas:delete':           'حذف ولاية',
  'wilayas:import':           'استيراد الولايات',
  'moughataa:read':           'عرض المقاطعات',
  'moughataa:create':         'إضافة مقاطعة',
  'moughataa:update':         'تعديل مقاطعة',
  'moughataa:delete':         'حذف مقاطعة',
  'moughataa:import':         'استيراد المقاطعات',
  'communes:read':            'عرض البلديات',
  'communes:create':          'إضافة بلدية',
  'communes:update':          'تعديل بلدية',
  'communes:delete':          'حذف بلدية',
  'communes:import':          'استيراد البلديات',
  'villages:read':            'عرض القرى',
  'villages:create':          'إضافة قرية',
  'villages:update':          'تعديل قرية',
  'villages:delete':          'حذف قرية',
  'villages:import':          'استيراد القرى',
  'banks:read':               'عرض البنوك',
  'banks:create':             'إضافة بنك',
  'banks:update':             'تعديل بنك',
  'banks:delete':             'حذف بنك',
  'salary_amounts:read':      'عرض مبالغ الرواتب',
  'salary_amounts:create':    'إضافة مبلغ راتب',
  'salary_amounts:delete':    'حذف مبلغ راتب',
  'users:read':               'عرض المستخدمين',
  'users:create':             'إضافة مستخدم',
  'users:update':             'تعديل مستخدم',
  'users:delete':             'حذف مستخدم',
  'roles:read':               'عرض الأدوار',
  'roles:create':             'إضافة دور',
  'roles:update':             'تعديل دور',
  'roles:delete':             'حذف دور',
};

export const ENTITY_LABELS = {
  employees:       'الموظفون',
  contracts:       'العقود',
  mahdaras:        'المحاضر',
  payment_batches: 'دفعات الدفع',
  employee_types:  'أنواع الموظفين',
  wilayas:         'الولايات',
  moughataa:       'المقاطعات',
  communes:        'البلديات',
  villages:        'القرى',
  banks:           'البنوك',
  salary_amounts:  'مبالغ الرواتب',
  users:           'المستخدمون',
  roles:           'الأدوار',
};
